export const NEW_NOTIFICATION_REQUEST = 'NEW_NOTIFICATION_REQUEST'
export const NEW_NOTIFICATION_SUCCESS = 'NEW_NOTIFICATION_SUCCESS'
export const NEW_NOTIFICATION_RESET =   'NEW_NOTIFICATION_RESET'
export const NEW_NOTIFICATION_FAIL =    'NEW_NOTIFICATION_FAIL'

export const GET_NOTIFICATIONS_REQUEST = 'GET_NOTIFICATIONS_REQUEST'
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS'
export const GET_NOTIFICATIONS_RESET =   'GET_NOTIFICATIONS_RESET'
export const GET_NOTIFICATIONS_FAIL =    'GET_NOTIFICATIONS_FAIL'

export const GET_MYNOTIFICATIONS_REQUEST = 'GET_MYNOTIFICATIONS_REQUEST'
export const GET_MYNOTIFICATIONS_SUCCESS = 'GET_MYNOTIFICATIONS_SUCCESS'
export const GET_MYNOTIFICATIONS_RESET =   'GET_MYNOTIFICATIONS_RESET'
export const GET_MYNOTIFICATIONS_FAIL =    'GET_MYNOTIFICATIONS_FAIL'

export const READ_MYNOTIFICATION_REQUEST = 'READ_MYNOTIFICATION_REQUEST'
export const READ_MYNOTIFICATION_SUCCESS = 'READ_MYNOTIFICATION_SUCCESS'
export const READ_MYNOTIFICATION_RESET =   'READ_MYNOTIFICATION_RESET'
export const READ_MYNOTIFICATION_FAIL =    'READ_MYNOTIFICATION_FAIL'

export const READ_ALLMYNOTIFICATION_REQUEST = 'READ_ALLMYNOTIFICATION_REQUEST'
export const READ_ALLMYNOTIFICATION_SUCCESS = 'READ_ALLMYNOTIFICATION_SUCCESS'
export const READ_ALLMYNOTIFICATION_RESET =   'READ_ALLMYNOTIFICATION_RESET'
export const READ_ALLMYNOTIFICATION_FAIL =    'READ_ALLMYNOTIFICATION_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
